/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ggpack;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 * Klasa <code>Main</code> tworzy okno interfejsu, zamyka aplikację, obsługuje
 * przyciski RYSUJ oraz CZYŚĆ, wprowadza dane z pól tekstowych, wyświetla wyniki
 * obliczeń, komentarze i prezentuje rysunek wygenerowany przez klasę
 * <code>DrawPanel</code>.
 *
 * @author Jacek Sobiecki
 * @author Piotr Szubert
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form GeoGebraUI
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_a = new javax.swing.JLabel();
        jTextField_a = new javax.swing.JTextField();
        jLabel_i = new javax.swing.JLabel();
        jLabel_b = new javax.swing.JLabel();
        jLabel_k = new javax.swing.JLabel();
        jLabel_c = new javax.swing.JLabel();
        jTextField_i = new javax.swing.JTextField();
        jTextField_b = new javax.swing.JTextField();
        jTextField_k = new javax.swing.JTextField();
        jLabel_m = new javax.swing.JLabel();
        jTextField_c = new javax.swing.JTextField();
        jTextField_m = new javax.swing.JTextField();
        jTextField_kat = new javax.swing.JTextField();
        jSlider1 = new javax.swing.JSlider();
        jLabel_kom = new javax.swing.JLabel();
        jButton_rys = new javax.swing.JButton();
        jButton_czysc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(20000, 50000));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel2.setMaximumSize(new java.awt.Dimension(200, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(280, 333));

        jLabel_a.setText("Parametr a");

        jTextField_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_a.setText("1.1");
        jTextField_a.setMinimumSize(new java.awt.Dimension(83, 26));
        jTextField_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_aMousePressed(evt);
            }
        });

        jLabel_i.setText("Parametr i");

        jLabel_b.setText("Parametr b");

        jLabel_k.setText("Parametr k");
        jLabel_k.setToolTipText("");

        jLabel_c.setText("Parametr c");

        jTextField_i.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_i.setText("2");
        jTextField_i.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_iMousePressed(evt);
            }
        });

        jTextField_b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_b.setText("1.6");
        jTextField_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_bMousePressed(evt);
            }
        });

        jTextField_k.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_k.setText("3");
        jTextField_k.setMinimumSize(new java.awt.Dimension(89, 26));
        jTextField_k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_kMousePressed(evt);
            }
        });

        jLabel_m.setText("Parametr m");

        jTextField_c.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_c.setText("4.2");
        jTextField_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_cMousePressed(evt);
            }
        });

        jTextField_m.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_m.setText("3");
        jTextField_m.setMinimumSize(new java.awt.Dimension(89, 26));
        jTextField_m.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_mMousePressed(evt);
            }
        });

        jTextField_kat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_kat.setText("3");
        jTextField_kat.setMinimumSize(new java.awt.Dimension(100, 26));
        jTextField_kat.setPreferredSize(new java.awt.Dimension(90, 26));
        jTextField_kat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_katMousePressed(evt);
            }
        });

        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(360);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setValue(0);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jButton_rys.setLabel("RYSUJ");
        jButton_rys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_rysActionPerformed(evt);
            }
        });

        jButton_czysc.setText("CZYSC");
        jButton_czysc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_czyscActionPerformed(evt);
            }
        });

        jLabel1.setText("kat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_rys)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_czysc))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_b)
                                .addComponent(jTextField_c, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_a, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_a, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_m, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jTextField_k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_i)
                            .addComponent(jLabel_k)
                            .addComponent(jLabel_m)
                            .addComponent(jTextField_i)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_kom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_b)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jTextField_kat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_c)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_a)
                    .addComponent(jLabel_i, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_i, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_b)
                    .addComponent(jLabel_k))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_c)
                    .addComponent(jLabel_m))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_kat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel_kom, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_rys)
                    .addComponent(jButton_czysc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField_a.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * Rysuje wykres
     * @param evt obiekt klasy java.awt.event.ActionEvent
     */
    private void jButton_rysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_rysActionPerformed
        // TODO add your handling code here:

        try {
            Data.a = Double.parseDouble(jTextField_a.getText());
            Data.b = Double.parseDouble(jTextField_b.getText());
            Data.c = Double.parseDouble(jTextField_c.getText());
            Data.i = Integer.parseInt(jTextField_i.getText());
            Data.k = Integer.parseInt(jTextField_k.getText());
            Data.m = Integer.parseInt(jTextField_m.getText());
            double kat = Double.parseDouble(jTextField_kat.getText());
            Data.kat = (kat * 180 / Math.PI);

            if (Data.a < 0) {
                throw new NumberFormatException();
            }
            if (Data.b < 0) {
                throw new NumberFormatException();
            }
            if (Data.c < 0) {
                throw new NumberFormatException();
            }
            if (Data.i < 0) {
                throw new NumberFormatException();
            }
            if (Data.k < 0) {
                throw new NumberFormatException();
            }
            if (Data.m < 0) {
                throw new NumberFormatException();
            }
            if (Data.kat < 0) {
                throw new NumberFormatException();
            }
            jPanel1.setLayout(new BorderLayout());
            JPanel dp = DrawPanel.createWoPanel();
            jPanel1.add(dp);
            jPanel1.validate();
            jLabel_kom.setText(String.valueOf("<html>Wartosc max :" + Data.max + "<br>Wartosc min :" + Data.min + "</html>"));
            jPanel1.setVisible(true);
        } catch (NumberFormatException e) {
            jPanel1.setVisible(false);
            jLabel_kom.setText("<html>Wprowadzone dane są niepoprawne <br> Wszystkie dane powinny byc > 0.0 <br> oraz wartosci i,k,m calkowite </html>");
        } catch (NullPointerException e) {
            jLabel_kom.setText("Wprowadzone dane nie są liczbami");
        }
        
    }//GEN-LAST:event_jButton_rysActionPerformed


    /**
     * Ustawia początkowe wartości parametrów oraz ukrywa wykres.
     * @param evt obiekt klasy java.awt.event.ActionEvent
     */
    private void jButton_czyscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_czyscActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        jTextField_a.setText("1.1");
        jTextField_b.setText("1.6");
        jTextField_c.setText("4.2");
        jTextField_i.setText("2");
        jTextField_k.setText("3");
        jTextField_m.setText("3");
        jTextField_kat.setText("3");
        jLabel_kom.setText("");
    }//GEN-LAST:event_jButton_czyscActionPerformed

    /**
     * Reaguje na zmianę położenia suwaka, ustawia wartość kąta.
     * @param evt obiekt klasy javax.swing.event.ChangeEvent
     */
    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        Data.kat = 0;
        Data.kat = jSlider1.getValue();
        jTextField_kat.setText(String.valueOf((jSlider1.getValue() * 0.017453)));

    }//GEN-LAST:event_jSlider1StateChanged

    private void jTextField_cMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_cMousePressed
        // TODO add your handling code here:
        jTextField_c.setText("");
    }//GEN-LAST:event_jTextField_cMousePressed

    private void jTextField_mMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_mMousePressed
        // TODO add your handling code here:
        jTextField_m.setText("");
    }//GEN-LAST:event_jTextField_mMousePressed

    private void jTextField_kMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_kMousePressed
        // TODO add your handling code here:
        jTextField_k.setText("");
    }//GEN-LAST:event_jTextField_kMousePressed

    private void jTextField_iMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_iMousePressed
        // TODO add your handling code here:
        jTextField_i.setText("");
    }//GEN-LAST:event_jTextField_iMousePressed

    private void jTextField_aMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_aMousePressed
        // TODO add your handling code here:
        jTextField_a.setText("");
    }//GEN-LAST:event_jTextField_aMousePressed

    private void jTextField_katMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_katMousePressed
        // TODO add your handling code here:
        jTextField_kat.setText("");
    }//GEN-LAST:event_jTextField_katMousePressed

    private void jTextField_bMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_bMousePressed
        // TODO add your handling code here:
        jTextField_b.setText("");
    }//GEN-LAST:event_jTextField_bMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Main().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_czysc;
    private javax.swing.JButton jButton_rys;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_a;
    private javax.swing.JLabel jLabel_b;
    private javax.swing.JLabel jLabel_c;
    private javax.swing.JLabel jLabel_i;
    private javax.swing.JLabel jLabel_k;
    private javax.swing.JLabel jLabel_kom;
    private javax.swing.JLabel jLabel_m;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField_a;
    private javax.swing.JTextField jTextField_b;
    private javax.swing.JTextField jTextField_c;
    private javax.swing.JTextField jTextField_i;
    private javax.swing.JTextField jTextField_k;
    private javax.swing.JTextField jTextField_kat;
    private javax.swing.JTextField jTextField_m;
    // End of variables declaration//GEN-END:variables
}
